// Main Components
export { default as NavigationMenu } from './NavigationMenu/NavigationMenu.vue'
export { default as Header } from './Header/Header.vue'

// Common Components (to be created)
export { default as Button } from './common/Button.vue'
export { default as Card } from './common/Card.vue'
export { default as SearchBar } from './common/SearchBar.vue'
export { default as Snackbar } from './common/Snackbar.vue'
export { default as ConfirmDialog } from './common/ConfirmDialog.vue'
export { default as Modal } from './common/Modal.vue'
export { default as Table } from './common/Table.vue'
export { default as VDataTable } from './common/VDataTable.vue'
export { default as VSelect } from './common/VSelect.vue'
export { default as CategoryDialog } from './common/CategoryDialog.vue'
export { default as JobDialog } from './common/JobDialog.vue'
export { default as JobDetailsDialog } from './common/JobDetailsDialog.vue'
export { default as JobSectionDialog } from './common/JobSectionDialog.vue'
export { default as JobRequestDetailsDialog } from './common/JobRequestDetailsDialog.vue'
export { default as JobRequestStateDialog } from './common/JobRequestStateDialog.vue'
export { default as NewsDialog } from './common/NewsDialog.vue'
export { default as DetailsDialog } from './common/DetailsDialog.vue'
export { default as FormattedDate } from './common/FormattedDate.vue'
export { default as Form } from './common/Form.vue'
export { default as Loading } from './common/Loading.vue'
export { default as Title } from './common/Title.vue'
export { default as EmptyState } from './common/EmptyState.vue'
export { default as StatusBadge } from './common/StatusBadge.vue'

// Dashboard Components (to be created)
export { default as DashboardStats } from './dashboard/DashboardStats.vue'
export { default as DashboardChart } from './dashboard/DashboardChart.vue'
export { default as RecentActivity } from './dashboard/RecentActivity.vue'

// Form Components (to be created)
export { default as Input } from './forms/Input.vue'
export { default as Select } from './forms/Select.vue'
export { default as Textarea } from './forms/Textarea.vue'
export { default as Checkbox } from './forms/Checkbox.vue'
export { default as Radio } from './forms/Radio.vue'
export { default as DatePicker } from './forms/DatePicker.vue'
export { default as FileUpload } from './forms/FileUpload.vue'
